permalink: /:year/:month/:day/:title.html

title: Mouleon
url: http://mouleon.com
feed: /atom.xml
author_info: <a href="http://Mouleon.github.io">Mouleon</a>
description: "Mouleon的个人博客"
keywords: 算法,C++,Python,Python爬虫,Mouleon,Blog,博客

paginate: 10
paginate_path: "page/:num/"
plugins: [jekyll-paginate]

highlighter: Rouge
since: 2019

cdn: https://cdn.jsdelivr.net/gh/Mouleon/mouleon.github.io
excerpt_separator:  '<!-- more -->'
